fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    gcc: "git://github.com/puppetlabs/puppetlabs-gcc"
    postgresql: "git://github.com/puppetlabs/puppetlabs-postgresql"
  symlinks:
    profile: "#{source_dir}"
