fixtures:
  repositories:
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    gcc: "git://github.com/puppetlabs/puppetlabs-gcc"
    postgresql: "git://github.com/puppetlabs/puppetlabs-postgresql"
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    ssh_keygen: "git://github.com/maestrodev/puppet-ssh_keygen"
  symlinks:
    profile: "#{source_dir}"
    gitolite: "../../../../gitolite"
