require 'rake'

require 'rspec/core/rake_task'

require 'rubygems'
require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'

RSpec::Core::RakeTask.new(:test) do |t|
  t.rspec_opts = ['--format=d']
  t.pattern = 'spec/*/*_spec.rb'
end
