# jenkins profile
# wget http://localhost:8085/jenkins/jnlpJars/jenkins-cli.jar
# java -jar jenkins-cli.jar \
#    -s http://localhost:8085/jenkins install-plugin
# NOTE: need to create git repo for config


$myvar = ['trac',
'git',
'email-ext',
'all-changes',
'build-environment',
'build-failure-analyzer',
'disk-usage',
'global-build-stats',
'log-parser',
'mttr',
'sloccount',
'warnings',
'extreme-feedback',
'conditional-buildstep',
'envinject',
'job-exporter',
'managed-scripts',
'python',
'rake',
'scons',
'template-project',
'buildresult-trigger',
'build-timeout',
'livescreenshot',
'ssh',
'timestamper',
'libvirt-slave',
'log-command',
'gatling',
'trac-publisher-plugin',
'compact-columns',
'custom-job-icon',
'email-ext-recipients-column',
'extra-columns',
'PrioritySorter',
'project-stats-plugin',
'uptime',
'analysis-core',
'analysis-collector',
'tasks',
'jobgenerator',
'build-monitor-plugin',
'ansicolor',
'thinBackup',
'build-alias-setter',
'buildcontext-capture',
'buildgraph-view',
'job-poll-action-plugin',
'jobConfigHistory',
'scm-sync-configuration',
'ssh-agent',
'storable-configs-plugin',
'rich-text-publisher-plugin',
'sitemonitor',
'text-finder',
'collapsing-console-sections',
'dashboard-view',
'embeddable-build-status',
'emotional-jenkins-plugin',
'greenballs',
'iphoneview',
'pragprog',
'shelve-project-plugin',
'sidebar-link',
]
# no CLI to delete plugins

class profile::jenkins {

}
